### ISSUE TITLE
[Feature] Add consolidated_exchange_rates_pass_through_columns pass through to NETSUITE2__TRANSACTION_DETAILS 

### ISSUE THREAD

**Issue by dubdesigndesk** [fivetran/dbt_netsuite#102]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I have added 

```
consolidated_exchange_rates_pass_through_columns:
    - name: "fromsubsidiary"
      alias: "trans_from_subsidiary_id"
    - name: "tosubsidiary"
      alias: "trans_to_subsidiary_id"
```
      
 To my project.yaml but the data is not being passed through. Your team had a look and stated 

"I have narrowed down the issue with fromsubsidiary not populating to the  NETSUITE2__TRANSACTION_DETAILS not having the configuration set up to pass through that column from consolidated_exchange_rates.
The next step would be to open a feature request in our netsuite repo so our team can look into adding that configuration in a future sprint!"

### Are you interested in contributing this feature?

- [ ] Yes.
- [x] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.
